- internal/metadatastorage/attestationcollection/parserstorer.go
- internal/metadatastorage/mysqlstore/mysql.go
- internal/metadatastorage/parser.go
- internal/metadatastorage/parserregistry/registry.go
To date Archivista has been limited to archive DSSE envelopes that
contain in-toto statements whose predicate is a Witness attestation
collection.
This commit introduces a change that allows Archivista to collect
information about DSSE envelopes that contain in-toto statements with
any arbitrary predicate.
Parsers and Storers can be added to collect more refined information
about these other predicates as we seek to add more support for them.
>  feat: collect subjects about in toto statements that contain other predicates

- .github/workflows/release.yml
Goreleaser was updated and now uses modules that require go >= 1.20, so our release action isn't working now.
We're holding off on updating go for our other action workflows as gokart doesn't work with go versions >= 1.20.
> fix: update goreleaser action to use go 1.20.x

- .github/workflows/release.yml
Updates to a newer version of the witness-run-action with the updated fulcio url as well as updates our tests to use the new fulcio url.
> fix: update github actions to use new fulcio url

- .github/workflows/verify-licence.yml
fix typo in license-check workflow "Archivist" to "Archivista"
> fix: license-check workflow Archivist > Archivista

- .github/workflows/update-pre-commit-hooks.yml
Using pre-commit can be very helpful for new contributors, but it can also bring some difficulties.
Sometimes, a contributor will have a different version of the hook, which is not part of his PR. We should keep it updated upstream to avoid different checks due to mismatched versions.
This commit adds a GHA workflow to submit updates (like dependabot)
> Auto-update pre-commit hooks PR

- cmd/archivistactl/cmd/retrieve.go
- cmd/archivistactl/cmd/search.go
- cmd/archivistactl/cmd/store.go
- internal/server/server.go
- pkg/api/download.go
- pkg/api/graphql.go
- pkg/api/store.go
The current "github.com/testifysec/archivista-api" was detached from the Archivista from the historical strategy by TestifySec.
TestifySec donated the Archivista project to the in-toto project, which makes more sense to the API package being part of the Archivista source code.
This commit adds "github.com/testifysec/archivista-api" as pkg in Archivista.
Closes #113
> refactoring: testifysec/archivista-api as a pkg

- .github/workflows/pipeline.yml
- .gitignore
- Makefile
- cmd/archivistactl/cmd/e2e_test.go
- cmd/archivistactl/cmd/retrieve.go
- cmd/archivistactl/cmd/retrieve_test.go
- cmd/archivistactl/cmd/root_test.go
- cmd/archivistactl/cmd/search.go
- cmd/archivistactl/cmd/search_test.go
- cmd/archivistactl/cmd/store.go
- test/deploy-services.sh
- test/invalid_payload.attestation.json
This commit improves the archivistactl end-to-end (e2e) tests moving from shell script to testify test suite.
The refactoring enables Archivista to have a better view of its test coverage. This improvement also includes tests for other assert levels, such as expected messages and data content, which will avoid issues such as regression.
> test: refactoring e2e & adding tests archivistactl

- cmd/archivistactl/cmd/retrieve_test.go
- pkg/api/download.go
- pkg/api/download_test.go
- pkg/api/graphql_test.go
- pkg/api/store_test.go
* Add unit tests for `pkg/api/store` coverage as 84%
* Add unit tests for `pkg/api/download` coverage as 85%
- The UT found a bug in the `DownloadWithWriter`. This bug returns nil
instead of error and affects users while downloading envelopes. For
example, the `archivistactl retrieve envelope` command, if giving an
invalid server or if the server is unavailable, will return no error.
- In the `archivistactl`, the user will behave the same when the
server is available, and there is no envelope with the expected
`gitoid`.
* Add unit tests for `pkg/api/graphql` coverage as 86%
> tests: Include tests for `pkg/api`

- cmd/archivistactl/cmd/root_test.go
Running `rootCmd.Execute` is the same as`Execute`, but for coverage it has an increase as it is a function declared in `cmd`.
> test: Minor change to increase the coverage

- .github/workflows/pipeline.yml
- .github/workflows/witness.yml
This commit consolidates the `tests` and `e2e` tests in one. The command `make tests` already run all the tests (unit and e2e).
This commit also includes in witness.yml the action to save the cover.out to be used later by the pipeline to download the cover.out and upload to the CodeCov.
> test: consolidate tests and add code coverage

- internal/objectstorage/filestore/file.go
- internal/objectstorage/filestore/file_test.go
We were not verifying input to archivista get/store request parameters
> Fix "uncontrolled data use"

- internal/server/server.go
Adds protection to the users while storing attestations
As Archivista relies on Object Storage/Filesystem to store the blob attestation and the SQL server to register the attestations for querying using GraphSQL, the flow needs to be consistent, as the services can fail.
Ideally, the Store should happen transactional and not finish with inconsistency: file available in the SQL but not in the metadata Storage, for example. If it happens, the user will query the SQL but will not be able to retrieve/download the attestation blob.
A minor fix is done in this PR, first adding the to the metadata storage and after registering in the SQL server.
So, if the metadata storage fails, it will not continue and save it in the SQL server.
None
> fix: consistency protection storing attestations

- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- entrypoint-dev.sh
- internal/server/server.go
- internal/server/server_test.go
Minor fix for the development environment, disabling vcs (`-disablevcs`)
- Fix the correct method for /api/v1/download as GET instead POST
- Include the parameter which allows users to try the endpoint directly
from swagger documentation
Archivista Download API returned 500 if a GitOID is available while
the user calls the `/v1/download/<gitoid>` (`/download/<gitoid>`)
endpoint.
It is not an Internal Server Error (500) but a not-found for the
GitOID endpoint.
Update Swagger documentation.
> Fix api responses

- README.md
- cmd/archivista/main.go
- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- internal/artifactstore/artifactstore.go
- internal/artifactstore/artifactstore_test.go
- internal/config/config.go
- internal/server/server.go
- internal/server/server_test.go
Support use case of private archivista deployments where getting witness
may be difficult. Also support use case of folks having custom builds of
witness to distribute. Extended to be a more generic artifact store for
additional tools.
Fixes #
> feat: add ability to distribute artifacts through archivista

- chart/Chart.yaml
- chart/README.md
Remove mention of testifysec from chart.
Fixes #258
> Remove mention of testifysec from chart.

- pkg/metadatastorage/attestationcollection/parser_registry.go
- pkg/metadatastorage/attestationcollection/parser_registry_test.go
- pkg/metadatastorage/attestationcollection/parserstorer.go
This commit introduces a flexible plugin system for archivists' parsers,
allowing new parsers to be registered dynamically. The system utilizes an
initialization function that registers parsers via a `Register` function. The
primary changes include:
- Creation of `parser_registry.go` to handle parser registration and storage.
- Modification of `parserstorer.go` to integrate the new parser registration
system and utilize registered parsers during attestation storage.
This system enhances the extensibility of the parser functionality and improves
maintainability by decoupling the parser registration from the core logic.
Changes:
- Added `internal/metadatastorage/attestationcollection/parser_registry.go` for
parser registration.
- Updated …
> feat: Implement plugin system for archivists' parsers

- .github/workflows/pipeline.yml
- .github/workflows/witness.yml
- .goreleaser.yaml
Our Dockerfile includes our migrations and Atlas to execute those migrations. However, the public image we are pushing is built with Ko and excludes these files/tools. This commit switches gorelease to build the image with the included Dockerfile.
Description
Fixes #
> chore(ci): build images with dockerfile instead of ko

- README.md
- cmd/archivista/main.go
- cmd/archivistactl/cmd/retrieve_test.go
- cmd/archivistactl/cmd/search_test.go
- pkg/config/config.go
- pkg/config/config_test.go
Fixes issue with large attestation uploads timing out. Also, tests on my local system are failing due to the error message being return as `connection reset` instead of `connection refused`. Happy to change to a stricter comparison if you have a suggestion on how to check for either error mesage.
> Add config options for http read and write timeouts

- CONTRIBUTING.md
- Makefile
> Update from docker-compose to docker compose

- .github/workflows/db-migrations.yml
- .github/workflows/witness.yml
- go.mod
- go.sum
This PR aligns the go versions from Dockerfile to the pipelines
Update some dependencies
Suppress PR #341
> chore: bump go version 1.21 to 1.22

- pkg/server/server.go
Error: pkg/server/server.go:468:18: printf: non-constant format string in call to github.com/sirupsen/logrus.Errorf (govet)
logrus.Errorf(fmt.Sprintf("failed to close artifact distribution file %s: %+v", distro.FileLocation, err))
> fix: golangci-lint warning (v1.60.x)

- chart/templates/deployment.yaml
This uses the existing `archivista.serviceAccountName` from helpers to explicitly set the `serviceAccountName` for pods. Without this change the pods still use the `default` service account even if a different service account is created by the helm chart when `serviceAccount.create` is true.
Fixes #370 
> fix: explicitly set serviceAccountName in deployment podspec

- .github/workflows/charts-release.yml
Add auto chart release and version control
- Allows user to use `helm repo` command
- Enable the project control of the Archivista charts versions
Action required:
Configure the repository GitHub Pages to use the branch `charts-page`
Please, see the branch `charts-page`
The charts will be available at https://in-toto.github.io/archivista
> build: add auto chart release and version control and Page for Charts

- chart/Chart.yaml
- chart/values.yaml
Release Archivista Chart 0.5.0
- update chart 0.5.0 to use latest archivista 0.5.3
> release archivista charts  0.5.0

- README.md
- entrypoint.sh
- pkg/config/config.go
- pkg/server/server.go
- pkg/server/server_test.go
- pkg/server/services.go
A user has expressed the desire to disable the SQL metadata store and graphql endpoints entirely, and just use Archivista to store and download attestations. This PR adds another config variable to support this, and disables both GraphQL and the SQL endpoint features if configured to do so.
Fixes #
> chore: disable sql connection when graphql is disabled

- .github/workflows/update-pre-commit-hooks.yml
Fix issue with automated PRs for pre-commit hooks.
> Write to a branch requires write permissions to content

- cmd/archivistactl/cmd/store.go
- pkg/api/download.go
- pkg/api/graphql.go
- pkg/api/structs.go
- pkg/api/upload.go
- pkg/http-client/client.go
- pkg/http-client/client_test.go
* Refactor package Archivista API
* Add package Archivista HTTP Client
> Refactoring pkg Archivista API and include new http client for Archivista

- pkg/objectstorage/filestore/file_test.go
fix: use high number port to prevent permissions error or conflicts on default port 80
> fix: flaky filestore test

- cmd/archivista/main.go
Issue was being encountered where configured LISTEN_On address and port were being disregarded when running with TLS enabled. This was happening because we were not using the configured listener.
Fixes #
> fix: use created listener when serving tls
